/**
 * The fictional "Demo village", generated relative to `now` (docs/build-plan.md §10).
 * Written as a handful of literal multi-row INSERTs so a whole seed/reset is one atomic D1 batch
 * (D1 caps bound parameters per query at 100, so we don't bind; every value here is generated by us and escaped).
 */
import { DEFAULT_CONFIG, type RequestKind } from "../../shared/types";
import { localParts, localToInstant } from "../../shared/rules";
import type { Db } from "../db";

export const TIMEZONE = "America/Toronto";
const HOUR = 3_600_000;
const DAY = 86_400_000;
const MIN = 60_000;

export interface SeedOptions {
  name: string;
  isSandbox: boolean;
  now: number;
  /** Keep these QR tokens (houseId → token), so a reset doesn't invalidate codes already handed out. */
  tokens?: Record<string, string>;
}

type Val = string | number | null;
type Rec = Record<string, Val>;

function mulberry32(seed: number) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const ALPHABET = "abcdefghijkmnpqrstuvwxyz23456789";
export function randomToken(len: number): string {
  const bytes = new Uint8Array(len);
  crypto.getRandomValues(bytes);
  let s = "";
  for (const b of bytes) s += ALPHABET[b % ALPHABET.length];
  return s;
}

const lit = (v: Val): string => {
  if (v === null) return "NULL";
  if (typeof v === "number") {
    if (!Number.isFinite(v)) throw new Error("seed: non-finite number");
    return String(v);
  }
  return `'${v.replace(/'/g, "''")}'`;
};

function inserts(table: string, rows: Rec[], maxLen = 60_000): string[] {
  if (!rows.length) return [];
  const cols = Object.keys(rows[0]!);
  const head = `INSERT INTO ${table} (${cols.join(", ")}) VALUES `;
  const out: string[] = [];
  let cur: string[] = [];
  let len = head.length;
  for (const r of rows) {
    const tuple = `(${cols.map((c) => lit(r[c] ?? null)).join(", ")})`;
    if (cur.length && len + tuple.length + 2 > maxLen) {
      out.push(head + cur.join(", "));
      cur = [];
      len = head.length;
    }
    cur.push(tuple);
    len += tuple.length + 2;
  }
  if (cur.length) out.push(head + cur.join(", "));
  return out;
}

/** Road-side house positions: [x, y] in metres. 48 of them. */
function housePositions(rand: () => number): [number, number][] {
  const j = () => Math.round((rand() - 0.5) * 16);
  const pts: [number, number][] = [];
  [180, 260, 340, 420, 580, 660, 760, 860, 960, 1060, 1160, 1220, 1380, 1460, 1560, 1660].forEach((x, i) =>
    pts.push([x + j(), (i % 2 ? 745 : 655) + j()]),
  );
  [320, 400, 480, 560, 630, 770, 840, 920, 1000, 1080, 1160, 1230].forEach((y, i) => pts.push([(i % 2 ? 545 : 455) + j(), y + j()]));
  [330, 410, 490, 570, 630, 770, 850, 930, 1010, 1090].forEach((y, i) => pts.push([(i % 2 ? 1345 : 1255) + j(), y + j()]));
  const shoreY = (x: number) => (x <= 1000 ? 250 + ((220 - 250) * (x - 300)) / 700 : 220 + ((260 - 220) * (x - 1000)) / 700);
  [350, 430, 620, 720, 820, 920, 1100, 1200, 1400, 1500].forEach((x) => pts.push([x + j(), Math.round(shoreY(x)) + 45 + j()]));
  return pts;
}

/** Open requests at seed time: [house number, kind, source, hours ago]. */
const OPEN: [number, RequestKind, "resident" | "lit_door" | "office", number][] = [
  [31, "emergency", "resident", 0.6],
  [7, "out", "resident", 30],
  [26, "out", "resident", 5],
  [3, "soon", "resident", 20],
  [18, "soon", "resident", 9],
  [40, "soon", "resident", 2.5],
  [12, "out", "lit_door", 3],
  [35, "soon", "office", 1.2],
  [20, "sewage", "resident", 10],
];

export function seedSql(villageId: string, opts: SeedOptions): string[] {
  const { now } = opts;
  const tz = TIMEZONE;
  const rand = mulberry32(20260926);
  const pick = <T>(xs: readonly T[]): T => xs[Math.floor(rand() * xs.length)]!;
  const vid = villageId;
  const houseId = (n: number) => `${vid}-house-${n}`;
  const truckId = (n: number) => `${vid}-truck-${n}`;
  /** Local wall-clock time `daysAgo` days before today (village time). */
  const today = localParts(now, tz);
  const at = (daysAgo: number, hour: number, minute = 0) => localToInstant(tz, today.year, today.month, today.day - daysAgo, hour, minute);

  // ── village, houses, trucks
  const villages: Rec[] = [
    { id: vid, name: opts.name, timezone: tz, config: JSON.stringify(DEFAULT_CONFIG), is_sandbox: opts.isSandbox ? 1 : 0, created_at: now },
  ];
  const positions = housePositions(rand);
  const tanks = [900, 1000, 1200, 1200, 1200, 1200, 1400, 1500, 1600, 1800, 2000];
  const forcedApp: Record<number, boolean> = { 14: true, 7: true, 31: true, 26: true, 12: false, 35: false };
  const houses: Rec[] = positions.map(([x, y], i) => {
    const n = i + 1;
    return {
      id: houseId(n),
      village_id: vid,
      label: `House ${n}`,
      x,
      y,
      tank_litres: pick(tanks),
      uses_app: (forcedApp[n] ?? rand() < 0.8) ? 1 : 0,
      qr_token: opts.tokens?.[houseId(n)] ?? (opts.isSandbox ? randomToken(12) : `${vid}-h${n}`),
    };
  });
  const tankOf = new Map(houses.map((h) => [h.id as string, h.tank_litres as number]));
  const usesApp = new Map(houses.map((h) => [h.id as string, h.uses_app === 1]));
  const trucks: Rec[] = [1, 2, 3, 4].map((n) => ({
    id: truckId(n),
    village_id: vid,
    label: `Truck ${n}`,
    kind: n === 4 ? "sewage" : "water",
    capacity_litres: 13600,
    status: "up",
  }));

  // ── truck down/back history (completed periods only; all trucks up now)
  const status: Rec[] = [];
  const period = (truck: number, startAgo: number, days: number, reason: string) => {
    const s = now - startAgo * DAY;
    status.push({ id: `${vid}-tse-${truck}-${startAgo}-d`, village_id: vid, truck_id: truckId(truck), kind: "down", reason, voice_note_id: null, occurred_at: s, received_at: s });
    status.push({ id: `${vid}-tse-${truck}-${startAgo}-b`, village_id: vid, truck_id: truckId(truck), kind: "back", reason: null, voice_note_id: null, occurred_at: s + days * DAY, received_at: s + days * DAY });
  };
  period(2, 10, 4, "heater");
  period(2, 40, 9, "pump");
  period(2, 80, 16, "starting");
  period(3, 25, 2, "tires");
  const truckDown = (n: number, t: number) =>
    status.some((e, i) => e.truck_id === truckId(n) && e.kind === "down" && t >= (e.occurred_at as number) && t < (status[i + 1]!.occurred_at as number));

  // ── daily truck checks
  const checks: Rec[] = [];
  const allOk = JSON.stringify({ starts: true, heater: true, pump: true, hoses: true, other: true });
  for (let d = 14; d >= 0; d--) {
    for (const n of [1, 2, 3, 4]) {
      const t = at(d, 7, 30 + n * 3);
      if (t > now || truckDown(n, t)) continue;
      checks.push({ id: `${vid}-chk-${d}-${n}`, village_id: vid, truck_id: truckId(n), items: allOk, passed: 1, voice_note_id: null, occurred_at: t, received_at: t });
    }
  }

  // ── history: served requests, delivered stops, a few couldn't-deliver stops
  const openHouses = new Set(OPEN.map(([n]) => houseId(n)));
  const requests: Rec[] = [];
  const stops: Rec[] = [];
  let rn = 0;
  let sn = 0;
  for (let d = 14; d >= 0; d--) {
    const perDay = 23 + Math.floor(rand() * 5);
    for (let k = 0; k < perDay; k++) {
      const minute = 8 * 60 + Math.floor(((k + rand()) / perDay) * 9 * 60);
      const t = at(d, Math.floor(minute / 60), minute % 60);
      if (t > now - 10 * MIN) continue;
      const sewage = k % 12 === 5;
      let houseNo = 1 + Math.floor(rand() * 48);
      if (d <= 2 && openHouses.has(houseId(houseNo))) houseNo = houseNo === 14 ? 15 : 14 + (houseNo % 3);
      const hid = houseId(houseNo);
      const upWater = [1, 2, 3].filter((n) => !truckDown(n, t));
      const truck = sewage ? 4 : pick(upWater.length ? upWater : [1]);
      const kind: RequestKind = sewage ? "sewage" : rand() < 0.04 ? "emergency" : rand() < 0.4 ? "out" : "soon";
      const app = usesApp.get(hid)!;
      const source = app ? "resident" : rand() < 0.7 ? "lit_door" : "office";
      const longWait = kind === "out" && rand() < 0.12;
      const created = source === "lit_door" ? t - (20 + Math.floor(rand() * 70)) * MIN : t - (longWait ? 25 + rand() * 9 : 1 + rand() * 18) * HOUR;
      const rid = `${vid}-r-${++rn}`;
      requests.push({ id: rid, village_id: vid, house_id: hid, kind, source, status: "served", created_at: Math.round(created), updated_at: Math.round(created), closed_at: t });
      if (rand() < 0.05 && !sewage) {
        const ft = t - Math.round((1 + rand() * 3) * HOUR);
        if (ft > created) {
          stops.push({
            id: `${vid}-s-${++sn}`, village_id: vid, house_id: hid, truck_id: truckId(truck), request_id: rid, driver_initials: pick(["JA", "PT", "MK"]),
            litres: 0, outcome: "failed", reason: pick(["road_blocked", "no_access", "no_access", "other"]), voice_note_id: null, occurred_at: ft, received_at: ft, voided_at: null,
          });
        }
      }
      const tank = tankOf.get(hid)!;
      stops.push({
        id: `${vid}-s-${++sn}`, village_id: vid, house_id: hid, truck_id: truckId(truck), request_id: rid, driver_initials: truck === 4 ? "LN" : pick(["JA", "PT", "MK"]),
        litres: sewage ? 0 : Math.round((tank * (0.6 + rand() * 0.4)) / 10) * 10, outcome: "delivered", reason: null, voice_note_id: null, occurred_at: t, received_at: t, voided_at: null,
      });
    }
  }

  // ── open requests
  for (const [n, kind, source, hoursAgo] of OPEN) {
    const created = Math.round(now - hoursAgo * HOUR);
    requests.push({ id: `${vid}-open-${n}`, village_id: vid, house_id: houseId(n), kind, source, status: "open", created_at: created, updated_at: created, closed_at: null });
  }
  // House 7 (out of water, 30 h) was tried and the road was blocked.
  const tried = Math.max(now - 30 * HOUR + 2 * HOUR, Math.min(at(1, 10, 40), now - HOUR));
  stops.push({
    id: `${vid}-s-${++sn}`, village_id: vid, house_id: houseId(7), truck_id: truckId(1), request_id: `${vid}-open-7`, driver_initials: "JA",
    litres: 0, outcome: "failed", reason: "road_blocked", voice_note_id: null, occurred_at: tried, received_at: tried, voided_at: null,
  });
  // House 22: frozen fill pipe, 3 days ago.
  const frozenAt = at(3, 11, 5);
  const frozenReq = `${vid}-r-frozen`;
  requests.push({ id: frozenReq, village_id: vid, house_id: houseId(22), kind: "out", source: "resident", status: "served", created_at: frozenAt - 6 * HOUR, updated_at: frozenAt - 6 * HOUR, closed_at: frozenAt + 5 * HOUR });
  stops.push({
    id: `${vid}-s-${++sn}`, village_id: vid, house_id: houseId(22), truck_id: truckId(3), request_id: frozenReq, driver_initials: "MK",
    litres: 0, outcome: "failed", reason: "frozen_pipe", voice_note_id: null, occurred_at: frozenAt, received_at: frozenAt, voided_at: null,
  });
  stops.push({
    id: `${vid}-s-${++sn}`, village_id: vid, house_id: houseId(22), truck_id: truckId(3), request_id: frozenReq, driver_initials: "MK",
    litres: Math.round(tankOf.get(houseId(22))! * 0.8 / 10) * 10, outcome: "delivered", reason: null, voice_note_id: null, occurred_at: frozenAt + 5 * HOUR, received_at: frozenAt + 5 * HOUR, voided_at: null,
  });

  // ── voice notes + confirmed log entries
  const notes: Rec[] = [];
  const logs: Rec[] = [];
  const voiceEntry = (key: string, t: number, truck: number | null, house: number | null, type: string, category: string | null, severity: string | null, summary: string, transcript: string) => {
    const id = `${vid}-vn-${key}`;
    notes.push({
      id, village_id: vid, truck_id: truck ? truckId(truck) : null, house_id: house ? houseId(house) : null, context: truck ? "check" : "stop", sample_id: null, audio: null,
      mime: "audio/webm", duration_s: 9, transcript, language: "en", draft: null, draft_source: null, status: "confirmed", created_at: t, processed_at: t + MIN,
    });
    logs.push({
      id, village_id: vid, voice_note_id: id, about_truck_id: truck ? truckId(truck) : null, about_house_id: house ? houseId(house) : null,
      type, category, severity, summary, source: "voice", occurred_at: t, confirmed_at: t + 3 * MIN,
    });
  };
  // Exactly two Truck 2 heater reports in the last 5 days: a third one live raises "check with mechanic".
  voiceEntry("heater-1", Math.min(at(4, 7, 42), now - 4 * DAY + HOUR), 2, null, "truck_problem", "heater", "care",
    "Heater grinding, cab slow to warm up", "Truck two, the heater's making that grinding noise, cab takes forever to warm up.");
  voiceEntry("heater-2", Math.min(at(2, 7, 51), now - 2 * DAY + HOUR), 2, null, "truck_problem", "heater", "care",
    "Heater noise again, fan cutting out", "Uh, the heater's making that noise again, truck two. Fan keeps cutting out.");
  voiceEntry("hose-1", at(9, 10, 15), 1, null, "truck_problem", "hose", "fine", "Small drip at the hose coupling", "Truck one, little drip at the hose coupling, still fine to drive.");
  voiceEntry("road-1", Math.min(at(1, 10, 42), now - HOUR), 1, 7, "road_blocked", null, null, "Snow drift blocking the lane to House 7", "Couldn't get to house seven, big drift across the lane.");
  voiceEntry("frozen-1", frozenAt + 2 * MIN, 3, 22, "house_problem", null, null, "Frozen fill pipe at House 22", "House twenty-two, the fill pipe is frozen solid, couldn't fill.");

  const sql = [
    ...inserts("villages", villages),
    ...inserts("houses", houses),
    ...inserts("trucks", trucks),
    ...inserts("truck_status_events", status),
    ...inserts("truck_checks", checks),
    ...inserts("requests", requests),
    ...inserts("stops", stops),
    ...inserts("voice_notes", notes),
    ...inserts("log_entries", logs),
  ];
  return sql;
}

const CHILD_TABLES = ["log_entries", "voice_notes", "truck_status_events", "truck_checks", "stops", "requests", "trucks", "houses"] as const;

export function deleteVillageSql(villageIdExpr: string): string[] {
  return [...CHILD_TABLES.map((t) => `DELETE FROM ${t} WHERE village_id IN (${villageIdExpr})`), `DELETE FROM villages WHERE id IN (${villageIdExpr})`];
}

/** Seed a new village. Fails (whole batch rolled back) if the village id already exists. */
export async function seedVillage(db: Db, villageId: string, opts: SeedOptions): Promise<void> {
  await db.batch(seedSql(villageId, opts).map((s) => db.prepare(s)));
}

/** Wipe a village and re-seed it, atomically. */
export async function resetVillage(db: Db, villageId: string, opts: SeedOptions): Promise<void> {
  const del = deleteVillageSql(lit(villageId));
  await db.batch([...del, ...seedSql(villageId, opts)].map((s) => db.prepare(s)));
}

/** Delete sandboxes created before `before`. */
export async function deleteOldSandboxes(db: Db, before: number): Promise<void> {
  const expr = `SELECT id FROM villages WHERE is_sandbox = 1 AND created_at < ${Math.floor(before)}`;
  await db.batch(deleteVillageSql(expr).map((s) => db.prepare(s)));
}
